In [1]:
import requests
import polars as pl
import json
from pprint import pprint
from zoneinfo import ZoneInfo
from datetime import datetime

# ── Config ──────────────────────────────────────────────
LAT      = 24.8607
LON      = 67.0011
TIMEZONE = 'Asia/Karachi'
DAYS     = 7

WEATHER_URL = 'https://api.open-meteo.com/v1/forecast'
AQI_URL     = 'https://air-quality-api.open-meteo.com/v1/air-quality'

In [2]:
weather_params = {
    'latitude':      LAT,
    'longitude':     LON,
    'timezone':      TIMEZONE,
    'forecast_days': DAYS,
    'hourly': ','.join([
        'temperature_2m',
        'relativehumidity_2m',
        'dewpoint_2m',
        'apparent_temperature',
        'precipitation',
        'rain',
        'snowfall',
        'weathercode',
        'pressure_msl',
        'surface_pressure',
        'cloudcover',
        'visibility',
        'windspeed_10m',
        'winddirection_10m',
        'windgusts_10m',
        'uv_index',
        'is_day',
    ])
}

aqi_params = {
    'latitude':      LAT,
    'longitude':     LON,
    'timezone':      TIMEZONE,
    'forecast_days': DAYS,
    'hourly': ','.join([
        'pm10',
        'pm2_5',
        'carbon_monoxide',
        'nitrogen_dioxide',
        'sulphur_dioxide',
        'ozone',
        'aerosol_optical_depth',
        'dust',
        'uv_index',
        'european_aqi',
        'us_aqi',
    ])
}

weather_resp = requests.get(WEATHER_URL, params=weather_params, timeout=30)
aqi_resp     = requests.get(AQI_URL,     params=aqi_params,     timeout=30)

weather_resp.raise_for_status()
aqi_resp.raise_for_status()

weather_raw = weather_resp.json()
aqi_raw     = aqi_resp.json()

print('Weather status:', weather_resp.status_code)
print('AQI status:    ', aqi_resp.status_code)

Weather status: 200
AQI status:     200

In [3]:
print('=== WEATHER TOP-LEVEL KEYS ===')
pprint(list(weather_raw.keys()))

print('\n=== WEATHER METADATA ===')
for k in ['latitude', 'longitude', 'elevation', 'timezone', 'timezone_abbreviation', 'utc_offset_seconds']:
    print(f'  {k}: {weather_raw.get(k)}')

print('\n=== WEATHER HOURLY FIELDS ===')
pprint(list(weather_raw['hourly'].keys()))

print('\n=== WEATHER UNITS ===')
pprint(weather_raw['hourly_units'])

print('\n=== AQI HOURLY FIELDS ===')
pprint(list(aqi_raw['hourly'].keys()))

print('\n=== AQI UNITS ===')
pprint(aqi_raw['hourly_units'])

=== WEATHER TOP-LEVEL KEYS ===
['latitude',
 'longitude',
 'generationtime_ms',
 'utc_offset_seconds',
 'timezone',
 'timezone_abbreviation',
 'elevation',
 'hourly_units',
 'hourly']

=== WEATHER METADATA ===
  latitude: 24.850615
  longitude: 66.992485
  elevation: 7.0
  timezone: Asia/Karachi
  timezone_abbreviation: GMT+5
  utc_offset_seconds: 18000

=== WEATHER HOURLY FIELDS ===
['time',
 'temperature_2m',
 'relativehumidity_2m',
 'dewpoint_2m',
 'apparent_temperature',
 'precipitation',
 'rain',
 'snowfall',
 'weathercode',
 'pressure_msl',
 'surface_pressure',
 'cloudcover',
 'visibility',
 'windspeed_10m',
 'winddirection_10m',
 'windgusts_10m',
 'uv_index',
 'is_day']

=== WEATHER UNITS ===
{'apparent_temperature': '°C',
 'cloudcover': '%',
 'dewpoint_2m': '°C',
 'is_day': '',
 'precipitation': 'mm',
 'pressure_msl': 'hPa',
 'rain': 'mm',
 'relativehumidity_2m': '%',
 'snowfall': 'cm',
 'surface_pressure': 'hPa',
 'temperature_2m': '°C',
 'time': 'iso8601',
 'uv_index': '',
 'visibility': 'm',
 'weathercode': 'wmo code',
 'winddirection_10m': '°',
 'windgusts_10m': 'km/h',
 'windspeed_10m': 'km/h'}

=== AQI HOURLY FIELDS ===
['time',
 'pm10',
 'pm2_5',
 'carbon_monoxide',
 'nitrogen_dioxide',
 'sulphur_dioxide',
 'ozone',
 'aerosol_optical_depth',
 'dust',
 'uv_index',
 'european_aqi',
 'us_aqi']

=== AQI UNITS ===
{'aerosol_optical_depth': '',
 'carbon_monoxide': 'μg/m³',
 'dust': 'μg/m³',
 'european_aqi': 'EAQI',
 'nitrogen_dioxide': 'μg/m³',
 'ozone': 'μg/m³',
 'pm10': 'μg/m³',
 'pm2_5': 'μg/m³',
 'sulphur_dioxide': 'μg/m³',
 'time': 'iso8601',
 'us_aqi': 'USAQI',
 'uv_index': ''}

In [4]:
print('=== FIRST WEATHER RECORD ===')
pprint({k: v[0] for k, v in weather_raw['hourly'].items()})

print('\n=== FIRST AQI RECORD ===')
pprint({k: v[0] for k, v in aqi_raw['hourly'].items()})

=== FIRST WEATHER RECORD ===
{'apparent_temperature': 36.1,
 'cloudcover': 7,
 'dewpoint_2m': 27.5,
 'is_day': 0,
 'precipitation': 0.0,
 'pressure_msl': 1002.2,
 'rain': 0.0,
 'relativehumidity_2m': 88,
 'snowfall': 0.0,
 'surface_pressure': 1001.4,
 'temperature_2m': 29.7,
 'time': '2026-06-09T00:00',
 'uv_index': 0.0,
 'visibility': 14860.0,
 'weathercode': 95,
 'winddirection_10m': 224,
 'windgusts_10m': 28.8,
 'windspeed_10m': 13.6}

=== FIRST AQI RECORD ===
{'aerosol_optical_depth': 0.4,
 'carbon_monoxide': 190.0,
 'dust': 31.0,
 'european_aqi': 68,
 'nitrogen_dioxide': 13.3,
 'ozone': 48.0,
 'pm10': 44.4,
 'pm2_5': 21.9,
 'sulphur_dioxide': 5.9,
 'time': '2026-06-09T00:00',
 'us_aqi': 83,
 'uv_index': 0.0}

In [5]:
# Polars reads the hourly dict directly — each key becomes a column
df_weather = pl.DataFrame(weather_raw['hourly'])
df_aqi     = pl.DataFrame(aqi_raw['hourly'])

# Parse time strings → Polars Datetime, then localize to Karachi
df_weather = df_weather.with_columns(
    pl.col('time')
      .str.strptime(pl.Datetime, '%Y-%m-%dT%H:%M')
      .dt.replace_time_zone(TIMEZONE)
      .alias('time')
)

df_aqi = df_aqi.with_columns(
    pl.col('time')
      .str.strptime(pl.Datetime, '%Y-%m-%dT%H:%M')
      .dt.replace_time_zone(TIMEZONE)
      .alias('time')
)

print('Weather shape:', df_weather.shape)
print('AQI shape:    ', df_aqi.shape)
print('\nWeather time range:', df_weather['time'].min(), '→', df_weather['time'].max())
print('AQI time range:    ', df_aqi['time'].min(),     '→', df_aqi['time'].max())

Weather shape: (168, 18)
AQI shape:     (168, 12)

Weather time range: 2026-06-09 00:00:00+05:00 → 2026-06-15 23:00:00+05:00
AQI time range:     2026-06-09 00:00:00+05:00 → 2026-06-15 23:00:00+05:00

In [6]:
df_weather.head()

shape: (5, 18)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬────────┐
│ time       ┆ temperatur ┆ relativehu ┆ dewpoint_ ┆ … ┆ winddirec ┆ windgusts ┆ uv_index ┆ is_day │
│ ---        ┆ e_2m       ┆ midity_2m  ┆ 2m        ┆   ┆ tion_10m  ┆ _10m      ┆ ---      ┆ ---    │
│ datetime[μ ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ i64    │
│ s, Asia/Ka ┆ f64        ┆ i64        ┆ f64       ┆   ┆ i64       ┆ f64       ┆          ┆        │
│ rachi]     ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪════════╡
│ 2026-06-09 ┆ 29.7       ┆ 88         ┆ 27.5      ┆ … ┆ 224       ┆ 28.8      ┆ 0.0      ┆ 0      │
│ 00:00:00   ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ PKT        ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ 2026-06-09 ┆ 29.6       ┆ 88         ┆ 27.4      ┆ … ┆ 225       ┆ 31.7      ┆ 0.0      ┆ 0      │
│ 01:00:00   ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ PKT        ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ 2026-06-09 ┆ 29.4       ┆ 90         ┆ 27.5      ┆ … ┆ 229       ┆ 32.4      ┆ 0.0      ┆ 0      │
│ 02:00:00   ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ PKT        ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ 2026-06-09 ┆ 29.2       ┆ 91         ┆ 27.6      ┆ … ┆ 231       ┆ 32.0      ┆ 0.0      ┆ 0      │
│ 03:00:00   ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ PKT        ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ 2026-06-09 ┆ 29.2       ┆ 91         ┆ 27.6      ┆ … ┆ 231       ┆ 32.8      ┆ 0.0      ┆ 0      │
│ 04:00:00   ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
│ PKT        ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆        │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴────────┘

In [7]:
df_aqi.head()

shape: (5, 12)
┌───────────────┬──────┬───────┬─────────────────┬───┬──────┬──────────┬──────────────┬────────┐
│ time          ┆ pm10 ┆ pm2_5 ┆ carbon_monoxide ┆ … ┆ dust ┆ uv_index ┆ european_aqi ┆ us_aqi │
│ ---           ┆ ---  ┆ ---   ┆ ---             ┆   ┆ ---  ┆ ---      ┆ ---          ┆ ---    │
│ datetime[μs,  ┆ f64  ┆ f64   ┆ f64             ┆   ┆ f64  ┆ f64      ┆ i64          ┆ i64    │
│ Asia/Karachi] ┆      ┆       ┆                 ┆   ┆      ┆          ┆              ┆        │
╞═══════════════╪══════╪═══════╪═════════════════╪═══╪══════╪══════════╪══════════════╪════════╡
│ 2026-06-09    ┆ 44.4 ┆ 21.9  ┆ 190.0           ┆ … ┆ 31.0 ┆ 0.0      ┆ 68           ┆ 83     │
│ 00:00:00 PKT  ┆      ┆       ┆                 ┆   ┆      ┆          ┆              ┆        │
│ 2026-06-09    ┆ 41.7 ┆ 20.5  ┆ 159.0           ┆ … ┆ 29.0 ┆ 0.0      ┆ 68           ┆ 82     │
│ 01:00:00 PKT  ┆      ┆       ┆                 ┆   ┆      ┆          ┆              ┆        │
│ 2026-06-09    ┆ 38.0 ┆ 18.8  ┆ 137.0           ┆ … ┆ 27.0 ┆ 0.0      ┆ 68           ┆ 81     │
│ 02:00:00 PKT  ┆      ┆       ┆                 ┆   ┆      ┆          ┆              ┆        │
│ 2026-06-09    ┆ 33.9 ┆ 17.2  ┆ 126.0           ┆ … ┆ 24.0 ┆ 0.0      ┆ 67           ┆ 81     │
│ 03:00:00 PKT  ┆      ┆       ┆                 ┆   ┆      ┆          ┆              ┆        │
│ 2026-06-09    ┆ 31.3 ┆ 15.9  ┆ 123.0           ┆ … ┆ 21.0 ┆ 0.0      ┆ 67           ┆ 80     │
│ 04:00:00 PKT  ┆      ┆       ┆                 ┆   ┆      ┆          ┆              ┆        │
└───────────────┴──────┴───────┴─────────────────┴───┴──────┴──────────┴──────────────┴────────┘

In [8]:
print('=== WEATHER SCHEMA ===')
print(df_weather.schema)

print('\n=== AQI SCHEMA ===')
print(df_aqi.schema)

=== WEATHER SCHEMA ===
Schema({'time': Datetime(time_unit='us', time_zone='Asia/Karachi'), 'temperature_2m': Float64, 'relativehumidity_2m': Int64, 'dewpoint_2m': Float64, 'apparent_temperature': Float64, 'precipitation': Float64, 'rain': Float64, 'snowfall': Float64, 'weathercode': Int64, 'pressure_msl': Float64, 'surface_pressure': Float64, 'cloudcover': Int64, 'visibility': Float64, 'windspeed_10m': Float64, 'winddirection_10m': Int64, 'windgusts_10m': Float64, 'uv_index': Float64, 'is_day': Int64})

=== AQI SCHEMA ===
Schema({'time': Datetime(time_unit='us', time_zone='Asia/Karachi'), 'pm10': Float64, 'pm2_5': Float64, 'carbon_monoxide': Float64, 'nitrogen_dioxide': Float64, 'sulphur_dioxide': Float64, 'ozone': Float64, 'aerosol_optical_depth': Float64, 'dust': Float64, 'uv_index': Float64, 'european_aqi': Int64, 'us_aqi': Int64})

In [9]:
def null_report(df: pl.DataFrame, name: str) -> pl.DataFrame:
    total = len(df)
    report = (
        df.null_count()
          .unpivot(variable_name='column', value_name='nulls')
          .with_columns(
              (pl.col('nulls') / total * 100).round(1).alias('null_%')
          )
          .filter(pl.col('nulls') > 0)
          .sort('nulls', descending=True)
    )
    print(f'=== {name} NULL REPORT (non-zero only) ===')
    if report.is_empty():
        print('No nulls found')
    else:
        print(report)
    return report

null_w = null_report(df_weather, 'WEATHER')
print()
null_a = null_report(df_aqi, 'AQI')

=== WEATHER NULL REPORT (non-zero only) ===
No nulls found

=== AQI NULL REPORT (non-zero only) ===
shape: (11, 3)
┌───────────────────────┬───────┬────────┐
│ column                ┆ nulls ┆ null_% │
│ ---                   ┆ ---   ┆ ---    │
│ str                   ┆ u32   ┆ f64    │
╞═══════════════════════╪═══════╪════════╡
│ pm10                  ┆ 42    ┆ 25.0   │
│ pm2_5                 ┆ 42    ┆ 25.0   │
│ carbon_monoxide       ┆ 42    ┆ 25.0   │
│ nitrogen_dioxide      ┆ 42    ┆ 25.0   │
│ sulphur_dioxide       ┆ 42    ┆ 25.0   │
│ …                     ┆ …     ┆ …      │
│ aerosol_optical_depth ┆ 42    ┆ 25.0   │
│ dust                  ┆ 42    ┆ 25.0   │
│ uv_index              ┆ 42    ┆ 25.0   │
│ european_aqi          ┆ 41    ┆ 24.4   │
│ us_aqi                ┆ 41    ┆ 24.4   │
└───────────────────────┴───────┴────────┘

In [10]:
print('=== WEATHER DESCRIBE ===')
print(df_weather.describe())

=== WEATHER DESCRIBE ===
shape: (9, 19)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ statistic  ┆ time      ┆ temperatu ┆ relativeh ┆ … ┆ winddirec ┆ windgusts ┆ uv_index ┆ is_day   │
│ ---        ┆ ---       ┆ re_2m     ┆ umidity_2 ┆   ┆ tion_10m  ┆ _10m      ┆ ---      ┆ ---      │
│ str        ┆ str       ┆ ---       ┆ m         ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64      │
│            ┆           ┆ f64       ┆ ---       ┆   ┆ f64       ┆ f64       ┆          ┆          │
│            ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆          ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ count      ┆ 168       ┆ 168.0     ┆ 168.0     ┆ … ┆ 168.0     ┆ 168.0     ┆ 168.0    ┆ 168.0    │
│ null_count ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0      ┆ 0.0      │
│ mean       ┆ 2026-06-1 ┆ 31.36131  ┆ 74.982143 ┆ … ┆ 253.11309 ┆ 41.614286 ┆ 2.168155 ┆ 0.583333 │
│            ┆ 2 11:30:0 ┆           ┆           ┆   ┆ 5         ┆           ┆          ┆          │
│            ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ std        ┆ null      ┆ 2.101893  ┆ 11.009236 ┆ … ┆ 13.798128 ┆ 8.333356  ┆ 2.734085 ┆ 0.494481 │
│ min        ┆ 2026-06-0 ┆ 28.9      ┆ 44.0      ┆ … ┆ 224.0     ┆ 24.5      ┆ 0.0      ┆ 0.0      │
│            ┆ 9 00:00:0 ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 25%        ┆ 2026-06-1 ┆ 29.6      ┆ 66.0      ┆ … ┆ 244.0     ┆ 34.6      ┆ 0.0      ┆ 0.0      │
│            ┆ 0 18:00:0 ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 50%        ┆ 2026-06-1 ┆ 30.8      ┆ 77.0      ┆ … ┆ 253.0     ┆ 40.7      ┆ 0.45     ┆ 1.0      │
│            ┆ 2 12:00:0 ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ 75%        ┆ 2026-06-1 ┆ 32.8      ┆ 85.0      ┆ … ┆ 260.0     ┆ 49.3      ┆ 4.2      ┆ 1.0      │
│            ┆ 4 05:00:0 ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│ max        ┆ 2026-06-1 ┆ 38.3      ┆ 91.0      ┆ … ┆ 344.0     ┆ 58.7      ┆ 7.7      ┆ 1.0      │
│            ┆ 5 23:00:0 ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
│            ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆           ┆          ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴──────────┘

In [11]:
print('=== AQI DESCRIBE ===')
print(df_aqi.describe())

=== AQI DESCRIBE ===
shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ time      ┆ pm10      ┆ pm2_5     ┆ … ┆ dust      ┆ uv_index ┆ european_ ┆ us_aqi    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ aqi       ┆ ---       │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64      ┆ ---       ┆ f64       │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆ f64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 168       ┆ 126.0     ┆ 126.0     ┆ … ┆ 126.0     ┆ 126.0    ┆ 127.0     ┆ 127.0     │
│ null_coun ┆ 0         ┆ 42.0      ┆ 42.0      ┆ … ┆ 42.0      ┆ 42.0     ┆ 41.0      ┆ 41.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ 2026-06-1 ┆ 66.622222 ┆ 25.981746 ┆ … ┆ 68.349206 ┆ 2.193254 ┆ 65.23622  ┆ 81.07874  │
│           ┆ 2 11:30:0 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ std       ┆ null      ┆ 45.323813 ┆ 12.496953 ┆ … ┆ 65.428351 ┆ 3.217088 ┆ 11.797536 ┆ 13.789579 │
│ min       ┆ 2026-06-0 ┆ 28.2      ┆ 14.6      ┆ … ┆ 17.0      ┆ 0.0      ┆ 42.0      ┆ 65.0      │
│           ┆ 9 00:00:0 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 25%       ┆ 2026-06-1 ┆ 41.9      ┆ 18.2      ┆ … ┆ 32.0      ┆ 0.0      ┆ 62.0      ┆ 73.0      │
│           ┆ 0 18:00:0 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 50%       ┆ 2026-06-1 ┆ 50.8      ┆ 21.9      ┆ … ┆ 46.0      ┆ 0.05     ┆ 65.0      ┆ 77.0      │
│           ┆ 2 12:00:0 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 75%       ┆ 2026-06-1 ┆ 74.3      ┆ 29.1      ┆ … ┆ 83.0      ┆ 3.55     ┆ 69.0      ┆ 85.0      │
│           ┆ 4 05:00:0 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ max       ┆ 2026-06-1 ┆ 247.7     ┆ 74.3      ┆ … ┆ 346.0     ┆ 10.65    ┆ 85.0      ┆ 110.0     │
│           ┆ 5 23:00:0 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0+05:00   ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [12]:
weather_times = set(df_weather['time'].to_list())
aqi_times     = set(df_aqi['time'].to_list())

only_weather = weather_times - aqi_times
only_aqi     = aqi_times - weather_times

print(f'Weather timestamps : {len(weather_times)}')
print(f'AQI timestamps     : {len(aqi_times)}')
print(f'Only in weather    : {len(only_weather)}')
print(f'Only in AQI        : {len(only_aqi)}')

if only_weather:
    print('\nMismatched weather times:', sorted(only_weather)[:5])
if only_aqi:
    print('\nMismatched AQI times:', sorted(only_aqi)[:5])

Weather timestamps : 168
AQI timestamps     : 168
Only in weather    : 0
Only in AQI        : 0

In [13]:
print('Weather time dtype   :', df_weather['time'].dtype)
print('utc_offset_seconds   :', weather_raw.get('utc_offset_seconds'), '(+5h for Karachi)')

# Show local vs UTC for first record
first_local = df_weather['time'][0]
first_utc   = df_weather.with_columns(
    pl.col('time').dt.convert_time_zone('UTC').alias('time_utc')
)['time_utc'][0]

print(f'\nFirst record (local): {first_local}')
print(f'First record (UTC)  : {first_utc}')

Weather time dtype   : Datetime(time_unit='us', time_zone='Asia/Karachi')
utc_offset_seconds   : 18000 (+5h for Karachi)

First record (local): 2026-06-09 00:00:00+05:00
First record (UTC)  : 2026-06-08 19:00:00+00:00

In [14]:
weather_diffs = (
    df_weather
    .with_columns(pl.col('time').diff().alias('delta'))
    .filter(pl.col('delta').is_not_null())
    ['delta']
    .unique()
)

aqi_diffs = (
    df_aqi
    .with_columns(pl.col('time').diff().alias('delta'))
    .filter(pl.col('delta').is_not_null())
    ['delta']
    .unique()
)

print('Weather time deltas (unique):', weather_diffs.to_list())
print('AQI time deltas (unique):    ', aqi_diffs.to_list())
print('\nGrain is uniform hourly:',
    len(weather_diffs) == 1 and len(aqi_diffs) == 1)

Weather time deltas (unique): [datetime.timedelta(seconds=3600)]
AQI time deltas (unique):     [datetime.timedelta(seconds=3600)]

Grain is uniform hourly: True

In [15]:
# Join is_day from weather into AQI for cross-check
df_merged = df_aqi.join(
    df_weather.select(['time', 'is_day']),
    on='time',
    how='inner'
)

aqi_cols = ['pm2_5', 'pm10', 'us_aqi', 'european_aqi', 'uv_index']

for col in aqi_cols:
    if col in df_merged.columns:
        day_nulls   = df_merged.filter(pl.col('is_day') == 1)[col].null_count()
        night_nulls = df_merged.filter(pl.col('is_day') == 0)[col].null_count()
        print(f'{col:25s}  day_nulls={day_nulls}  night_nulls={night_nulls}')

pm2_5                      day_nulls=28  night_nulls=14
pm10                       day_nulls=28  night_nulls=14
us_aqi                     day_nulls=27  night_nulls=14
european_aqi               day_nulls=27  night_nulls=14
uv_index                   day_nulls=28  night_nulls=14

In [16]:
df_weather.glimpse()

Rows: 168
Columns: 18
$ time                 <datetime[μs, Asia/Karachi]> 2026-06-09 00:00:00+05:00, 2026-06-09 01:00:00+05:00, 2026-06-09 02:00:00+05:00, 2026-06-09 03:00:00+05:00, 2026-06-09 04:00:00+05:00, 2026-06-09 05:00:00+05:00, 2026-06-09 06:00:00+05:00, 2026-06-09 07:00:00+05:00, 2026-06-09 08:00:00+05:00, 2026-06-09 09:00:00+05:00
$ temperature_2m                              <f64> 29.7, 29.6, 29.4, 29.2, 29.2, 29.2, 29.3, 30.0, 31.1, 32.0
$ relativehumidity_2m                         <i64> 88, 88, 90, 91, 91, 91, 90, 85, 77, 73
$ dewpoint_2m                                 <f64> 27.5, 27.4, 27.5, 27.6, 27.6, 27.6, 27.4, 27.2, 26.6, 26.5
$ apparent_temperature                        <f64> 36.1, 35.9, 35.7, 35.6, 35.6, 35.4, 35.3, 35.4, 35.9, 36.8
$ precipitation                               <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ rain                                        <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ snowfall                                    <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ weathercode                                 <i64> 95, 95, 95, 95, 95, 95, 95, 95, 95, 95
$ pressure_msl                                <f64> 1002.2, 1001.6, 1001.1, 1001.0, 1000.8, 1001.1, 1001.4, 1001.7, 1002.0, 1002.0
$ surface_pressure                            <f64> 1001.4, 1000.8, 1000.3, 1000.2, 1000.0, 1000.3, 1000.6, 1000.9, 1001.2, 1001.2
$ cloudcover                                  <i64> 7, 9, 6, 6, 2, 9, 3, 22, 41, 25
$ visibility                                  <f64> 14860.0, 14580.0, 14780.0, 12620.0, 12900.0, 12200.0, 13980.0, 15100.0, 17160.0, 17620.0
$ windspeed_10m                               <f64> 13.6, 14.0, 14.7, 14.8, 14.2, 16.0, 16.4, 19.1, 20.4, 19.8
$ winddirection_10m                           <i64> 224, 225, 229, 231, 231, 239, 251, 256, 265, 263
$ windgusts_10m                               <f64> 28.8, 31.7, 32.4, 32.0, 32.8, 32.8, 33.1, 36.0, 38.5, 40.3
$ uv_index                                    <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 1.45, 3.05
$ is_day                                      <i64> 0, 0, 0, 0, 0, 0, 1, 1, 1, 1

In [17]:
df_aqi.glimpse()

Rows: 168
Columns: 12
$ time                  <datetime[μs, Asia/Karachi]> 2026-06-09 00:00:00+05:00, 2026-06-09 01:00:00+05:00, 2026-06-09 02:00:00+05:00, 2026-06-09 03:00:00+05:00, 2026-06-09 04:00:00+05:00, 2026-06-09 05:00:00+05:00, 2026-06-09 06:00:00+05:00, 2026-06-09 07:00:00+05:00, 2026-06-09 08:00:00+05:00, 2026-06-09 09:00:00+05:00
$ pm10                                         <f64> 44.4, 41.7, 38.0, 33.9, 31.3, 29.9, 28.2, 29.0, 32.9, 36.8
$ pm2_5                                        <f64> 21.9, 20.5, 18.8, 17.2, 15.9, 15.2, 14.6, 15.2, 17.7, 19.4
$ carbon_monoxide                              <f64> 190.0, 159.0, 137.0, 126.0, 123.0, 136.0, 180.0, 240.0, 275.0, 261.0
$ nitrogen_dioxide                             <f64> 13.3, 10.2, 7.6, 6.1, 5.0, 4.4, 5.6, 7.3, 8.1, 7.2
$ sulphur_dioxide                              <f64> 5.9, 5.1, 4.5, 4.1, 3.9, 3.7, 4.1, 4.7, 5.1, 5.2
$ ozone                                        <f64> 48.0, 51.0, 54.0, 55.0, 57.0, 59.0, 57.0, 55.0, 56.0, 64.0
$ aerosol_optical_depth                        <f64> 0.4, 0.41, 0.41, 0.4, 0.39, 0.38, 0.36, 0.34, 0.33, 0.32
$ dust                                         <f64> 31.0, 29.0, 27.0, 24.0, 21.0, 20.0, 18.0, 17.0, 17.0, 21.0
$ uv_index                                     <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.55, 1.9, 4.2
$ european_aqi                                 <i64> 68, 68, 68, 67, 67, 66, 66, 65, 65, 64
$ us_aqi                                       <i64> 83, 82, 81, 81, 80, 79, 79, 78, 77, 76

# For Pakistan

In [18]:
import geonamescache
import requests
import json
from datetime import date, timedelta
from pathlib import Path

# ── Pakistan cities ──────────────────────────────────────
gc = geonamescache.GeonamesCache()
all_cities = gc.get_cities()

END_DATE   = date.today().strftime('%Y-%m-%d')
START_DATE = (date.today() - timedelta(days=7)).strftime('%Y-%m-%d')

pk_cities = [
    {
        'geonameid': gid,
        'city':      city['name'],
        'province':  city['admin1code'],
        'latitude':  float(city['latitude']),
        'longitude': float(city['longitude']),
        'population': city['population'],
        'timezone':  city['timezone'],
    }
    for gid, city in all_cities.items()
    if city['countrycode'] == 'PK'
]

print(f'Total cities to fetch: {len(pk_cities)}')

# ── API params ───────────────────────────────────────────
WEATHER_URL = 'https://api.open-meteo.com/v1/forecast'
AQI_URL     = 'https://air-quality-api.open-meteo.com/v1/air-quality'
DAYS        = 7

WEATHER_FIELDS = ','.join([
    'temperature_2m', 'relativehumidity_2m', 'dewpoint_2m',
    'apparent_temperature', 'precipitation', 'rain', 'snowfall',
    'weathercode', 'pressure_msl', 'surface_pressure', 'cloudcover',
    'visibility', 'windspeed_10m', 'winddirection_10m', 'windgusts_10m',
    'uv_index', 'is_day',
])

AQI_FIELDS = ','.join([
    'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide',
    'sulphur_dioxide', 'ozone', 'aerosol_optical_depth',
    'dust', 'uv_index', 'european_aqi', 'us_aqi',
])

# ── Fetch ────────────────────────────────────────────────
weather_results = {}
aqi_results     = {}
failed          = []

for i, city in enumerate(pk_cities):
    name = city['city']
    lat  = city['latitude']
    lon  = city['longitude']
    tz   = city['timezone']

    print(f'[{i+1}/{len(pk_cities)}] {name}', end=' ... ')

    try:
        w = requests.get(WEATHER_URL, params={
            'latitude':   lat, 'longitude': lon,
            'timezone':   tz,
            'start_date': START_DATE,
            'end_date':   END_DATE,        # today — no future hours
            'hourly':     WEATHER_FIELDS,
        }, timeout=30)
        w.raise_for_status()

        a = requests.get(AQI_URL, params={
            'latitude':   lat, 'longitude': lon,
            'timezone':   tz,
            'start_date': START_DATE,
            'end_date':   END_DATE,
            'hourly':     AQI_FIELDS,
        }, timeout=30)
        a.raise_for_status()

        weather_results[name] = {'meta': city, 'data': w.json()}
        aqi_results[name]     = {'meta': city, 'data': a.json()}
        print('OK')

    except Exception as e:
        print(f'FAILED — {e}')
        failed.append(name)

# ── Save raw JSON ────────────────────────────────────────
Path('raw').mkdir(exist_ok=True)
with open('raw/weather_pakistan.json', 'w') as f:
    json.dump(weather_results, f, indent=2)
with open('raw/aqi_pakistan.json', 'w') as f:
    json.dump(aqi_results, f, indent=2)

print(f'\nDone. Success: {len(weather_results)}  Failed: {len(failed)}')
if failed:
    print('Failed cities:', failed)

Total cities to fetch: 328
[1/328] Chuhar Jamali ... OK
[2/328] Rawalakot ... OK
[3/328] Pir Jo Goth ... OK
[4/328] Khairpur Mir’s ... OK
[5/328] Zhob ... OK
[6/328] Zaida ... OK
[7/328] Zahir Pir ... OK
[8/328] Zafarwal ... OK
[9/328] Yazman ... OK
[10/328] Wazirabad ... OK
[11/328] Chak Five Hundred Seventy-five ... OK
[12/328] Warah ... OK
[13/328] Vihari ... OK
[14/328] Utmanzai ... OK
[15/328] Uthal ... OK
[16/328] Usta Muhammad ... OK
[17/328] Umarkot ... OK
[18/328] Ubauro ... OK
[19/328] Turbat ... OK
[20/328] Tordher ... OK
[21/328] Topi ... OK
[22/328] Toba Tek Singh ... OK
[23/328] Thul ... OK
[24/328] Thatta ... OK
[25/328] Tharu Shah ... OK
[26/328] Taunsa ... OK
[27/328] Tank ... OK
[28/328] Tangi ... OK
[29/328] Tando Muhammad Khan ... OK
[30/328] Tando Jam ... OK
[31/328] Tando Allahyar ... OK
[32/328] Tando Adam ... OK
[33/328] Tandlianwala ... OK
[34/328] Talhar ... OK
[35/328] Talamba ... OK
[36/328] Talagang ... OK
[37/328] Thal ... OK
[38/328] Swabi ... OK
[39/328] Surkhpur ... OK
[40/328] Sukkur ... OK
[41/328] Sukheke Mandi ... OK
[42/328] Sodhri ... OK
[43/328] Skardu ... OK
[44/328] Sita Road ... OK
[45/328] Sinjhoro ... OK
[46/328] Sillanwali ... OK
[47/328] Sibi ... OK
[48/328] Sialkot ... OK
[49/328] Shujaabad ... OK
[50/328] Shorkot ... OK
[51/328] Shikarpur ... OK
[52/328] Shekhupura ... OK
[53/328] Sharqpur Sharif ... OK
[54/328] Shakargarh ... OK
[55/328] Shahr Sultan ... OK
[56/328] Shahpur Chakar ... OK
[57/328] Shahkot ... OK
[58/328] Shahdadpur ... OK
[59/328] Shahdad Kot ... OK
[60/328] Shabqadar ... OK
[61/328] Sehwan ... OK
[62/328] Sargodha ... OK
[63/328] Sarai Sidhu ... OK
[64/328] Sarai Naurang ... OK
[65/328] Sarai Alamgir ... OK
[66/328] Sangla Hill ... OK
[67/328] Sanghar ... OK
[68/328] Sambrial ... OK
[69/328] Sakrand ... OK
[70/328] Sahiwal ... OK
[71/328] Sahiwal ... OK
[72/328] Saddiqabad ... OK
[73/328] Rohri ... OK
[74/328] Renala Khurd ... OK
[75/328] Rawalpindi ... OK
[76/328] Ratodero ... OK
[77/328] Ranipur ... OK
[78/328] Rajanpur ... OK
[79/328] Raja Jang ... OK
[80/328] Raiwind ... OK
[81/328] Rahim Yar Khan ... OK
[82/328] Goth Radhan ... OK
[83/328] Rabwah ... OK
[84/328] Quetta ... OK
[85/328] Kambar ... OK
[86/328] Qadirpur Ran ... OK
[87/328] Pishin ... OK
[88/328] Pir Mahal ... OK
[89/328] Pindi Gheb ... OK
[90/328] Pindi Bhattian ... OK
[91/328] Pind Dadan Khan ... OK
[92/328] Phalia ... OK
[93/328] Peshawar ... OK
[94/328] Pattoki ... OK
[95/328] Pasrur ... OK
[96/328] Pasni ... OK
[97/328] Pano Aqil ... OK
[98/328] Pakpattan ... OK
[99/328] Paharpur ... OK
[100/328] Pad Idan ... OK
[101/328] Pabbi ... OK
[102/328] Okara ... OK
[103/328] Nushki ... OK
[104/328] New Mirpur City ... OK
[105/328] Nawabshah ... OK
[106/328] Naushahro Firoz ... OK
[107/328] Naushahra Virkan ... OK
[108/328] Naudero ... OK
[109/328] Nasirabad ... OK
[110/328] Narowal ... OK
[111/328] Narang Mandi ... OK
[112/328] Naukot ... OK
[113/328] Nankana Sahib ... OK
[114/328] Muzaffargarh ... OK
[115/328] Muzaffarābād ... OK
[116/328] Mustafabad ... OK
[117/328] Murree ... OK
[118/328] Muridke ... OK
[119/328] Multan ... OK
[120/328] Moro ... OK
[121/328] Model Town ... OK
[122/328] Mithi ... OK
[123/328] Mitha Tiwana ... OK
[124/328] Mirpur Mathelo ... OK
[125/328] Mirpur Khas ... OK
[126/328] Mingora ... OK
[127/328] Minchianabad ... OK
[128/328] Mianwali ... OK
[129/328] Mian Sahib ... OK
[130/328] Mian Channun ... OK
[131/328] Mehrabpur ... OK
[132/328] Mehar ... OK
[133/328] Matli ... OK
[134/328] Matiari ... OK
[135/328] Mastung ... OK
[136/328] Mardan ... OK
[137/328] Mansehra ... OK
[138/328] Manjhand ... OK
[139/328] Mangla ... OK
[140/328] Mandi Bahauddin ... OK
[141/328] Mananwala ... OK
[142/328] Mamu Kanjan ... OK
[143/328] Malir Cantonment ... OK
[144/328] Malakwal ... OK
[145/328] Mailsi ... OK
[146/328] Mach ... OK
[147/328] Loralai ... OK
[148/328] Lodhran ... OK
[149/328] Layyah ... OK
[150/328] Larkana ... OK
[151/328] Lalian ... OK
[152/328] Lala Musa ... OK
[153/328] Lakki ... OK
[154/328] Lahore ... OK
[155/328] Ladhewala Waraich ... OK
[156/328] Lachi ... OK
[157/328] Kunri ... OK
[158/328] Kunjah ... OK
[159/328] Kundian ... OK
[160/328] Kulachi ... OK
[161/328] Kot Samaba ... OK
[162/328] Kotri ... OK
[163/328] Kot Radha Kishan ... OK
[164/328] Kot Mumin ... OK
[165/328] Kot Malik Barkhurdar ... OK
[166/328] Kotli Loharan ... OK
[167/328] Kotli ... OK
[168/328] Kot Ghulam Muhammad ... OK
[169/328] Kot Diji ... OK
[170/328] Kot Addu ... OK
[171/328] Kohat ... OK
[172/328] Khuzdar ... OK
[173/328] Khushāb ... OK
[174/328] Khurarianwala ... OK
[175/328] Khewra ... OK
[176/328] Kharian ... OK
[177/328] Kharan ... OK
[178/328] Khanpur ... OK
[179/328] Khanpur Mahar ... OK
[180/328] Khangarh ... OK
[181/328] Khangah Dogran ... OK
[182/328] Khalabat ... OK
[183/328] Khairpur Nathan Shah ... OK
[184/328] Khairpur Tamewah ... OK
[185/328] Khairpur ... OK
[186/328] Kasur ... OK
[187/328] Kashmor ... OK
[188/328] Karor ... OK
[189/328] Karachi ... OK
[190/328] Kanganpur ... OK
[191/328] Kandiaro ... OK
[192/328] Kandhkot ... OK
[193/328] Kamra ... OK
[194/328] Kamoke ... OK
[195/328] Chak One Hundred Twenty Nine Left ... OK
[196/328] Kamar Mushani ... OK
[197/328] Kamalia ... OK
[198/328] Kalur Kot ... OK
[199/328] Kallar Kahar ... OK
[200/328] Kaleke Mandi ... OK
[201/328] Kalat ... OK
[202/328] Kalabagh ... OK
[203/328] Kahuta ... OK
[204/328] Kahror Pakka ... OK
[205/328] Kahna Nau ... OK
[206/328] Kabirwala ... OK
[207/328] Johi ... OK
[208/328] Jiwani ... OK
[209/328] Chak Jhumra ... OK
[210/328] Jhol ... OK
[211/328] Jhelum ... OK
[212/328] Jhawarian ... OK
[213/328] Jhang Sadr ... OK
[214/328] Jauharabad ... OK
[215/328] Jatoi Shimali ... OK
[216/328] Jaranwala ... OK
[217/328] Jand ... OK
[218/328] Jampur ... OK
[219/328] Jalalpur Pirwala ... OK
[220/328] Jalalpur Jattan ... OK
[221/328] Jahanian Shah ... OK
[222/328] Jaglot ... OK
[223/328] Jacobabad ... OK
[224/328] Islamabad ... OK
[225/328] Hyderabad ... OK
[226/328] Hujra Shah Muqim ... OK
[227/328] Hingorja ... OK
[228/328] Hazro City ... OK
[229/328] Havelian ... OK
[230/328] Haveli Lakha ... OK
[231/328] Hasilpur ... OK
[232/328] Chak Thirty-one -Eleven Left ... OK
[233/328] Harunabad ... OK
[234/328] Harnoli ... OK
[235/328] Haripur ... OK
[236/328] Hangu ... OK
[237/328] Hala ... OK
[238/328] Hafizabad ... OK
[239/328] Hadali ... OK
[240/328] Gwadar ... OK
[241/328] Gujrat ... OK
[242/328] Gujranwala ... OK
[243/328] Gujar Khan ... OK
[244/328] Gojra ... OK
[245/328] Gilgit ... OK
[246/328] Ghotki ... OK
[247/328] Ghauspur ... OK
[248/328] Gharo ... OK
[249/328] Garh Maharaja ... OK
[250/328] Gambat ... OK
[251/328] Fort Abbas ... OK
[252/328] Fazilpur ... OK
[253/328] Fatehpur ... OK
[254/328] Faruka ... OK
[255/328] Faqirwali ... OK
[256/328] Faisalabad ... OK
[257/328] Eminabad ... OK
[258/328] Dunyapur ... OK
[259/328] Dunga Bunga ... OK
[260/328] Dullewala ... OK
[261/328] Upper Dir ... OK
[262/328] Dipalpur ... OK
[263/328] Dinga ... OK
[264/328] Dijkot ... OK
[265/328] Digri ... OK
[266/328] Dhoro Naro ... OK
[267/328] Dhanot ... OK
[268/328] Dera Ismail Khan ... OK
[269/328] Dera Ghazi Khan ... OK
[270/328] Dera Bugti ... OK
[271/328] Daur ... OK
[272/328] Daud Khel ... OK
[273/328] Daska Kalan ... OK
[274/328] Darya Khan ... OK
[275/328] Dajal ... OK
[276/328] Dadu ... OK
[277/328] Dadhar ... OK
[278/328] Chunian ... OK
[279/328] Chuhar Kana ... OK
[280/328] Chhor ... OK
[281/328] Choa Saidan Shah ... OK
[282/328] Chishtian ... OK
[283/328] Chiniot ... OK
[284/328] Chichawatni ... OK
[285/328] Chawinda ... OK
[286/328] Charsadda ... OK
[287/328] Chaman ... OK
[288/328] Chakwal ... OK
[289/328] Chak Azam Sahu ... OK
[290/328] Burewala ... OK
[291/328] Bhopalwala ... OK
[292/328] Bhit Shah ... OK
[293/328] Bhimber ... OK
[294/328] Bhera ... OK
[295/328] Bhawana ... OK
[296/328] Bhan ... OK
[297/328] Bhalwal ... OK
[298/328] Bhakkar ... OK
[299/328] Mianke Mor ... OK
[300/328] Bela ... OK
[301/328] Bat Khela ... OK
[302/328] Battagram ... OK
[303/328] Basirpur ... OK
[304/328] Bannu ... OK
[305/328] Bahawalpur ... OK
[306/328] Bahawalnagar ... OK
[307/328] Bagh ... OK
[308/328] Badin ... OK
[309/328] Baddomalhi ... OK
[310/328] Attock City ... OK
[311/328] Arifwala ... OK
[312/328] Aman Garh ... OK
[313/328] Alipur ... OK
[314/328] Akora ... OK
[315/328] Ahmadpur East ... OK
[316/328] Abbottabad ... OK
[317/328] Bahawalnagar ... OK
[318/328] Nowshera Cantonment ... OK
[319/328] Ahmadpur Sial ... OK
[320/328] New Badah ... OK
[321/328] Musa Banda/Musa khan kallay ... OK
[322/328] Setharja Old ... OK
[323/328] Sook Kalan ... OK
[324/328] Risalpur Cantonment ... OK
[325/328] Malakwal City ... OK
[326/328] Karachi University Employees Co-operative Housing Society ... OK
[327/328] Arif Wala ... OK
[328/328] Wah Cantt ... OK

Done. Success: 326  Failed: 0

In [34]:
with open('raw/weather_pakistan.json') as f:
    raw = json.load(f)

dfs = []
for city_name, payload in raw.items():
    meta   = payload['meta']
    hourly = payload['data']['hourly']

    df = (
        pl.DataFrame(hourly)
        .with_columns([
            pl.col('time')
              .str.strptime(pl.Datetime, '%Y-%m-%dT%H:%M')
              .dt.replace_time_zone('Asia/Karachi'),
            pl.lit(meta['geonameid']).alias('geonameid'),
            pl.lit(meta['city']).alias('city'),
            pl.lit(meta['province']).alias('province'),
            pl.lit(meta['latitude']).alias('latitude'),
            pl.lit(meta['longitude']).alias('longitude'),
            pl.lit(meta['timezone']).alias('timezone'),
            pl.lit(meta['population']).alias('population'),
        ])
    )
    dfs.append(df)

weather_df = pl.concat(dfs)

with open(r'raw\aqi_pakistan.json') as f:
    raw = json.load(f)

dfs = []
for city_name, payload in raw.items():
    meta   = payload['meta']
    hourly = payload['data']['hourly']

    df = (
        pl.DataFrame(hourly)
        .with_columns([
            pl.col('time')
              .str.strptime(pl.Datetime, '%Y-%m-%dT%H:%M')
              .dt.replace_time_zone('Asia/Karachi'),
            pl.lit(meta['geonameid']).alias('geonameid'),
            pl.lit(meta['city']).alias('city'),
            pl.lit(meta['province']).alias('province'),
            pl.lit(meta['latitude']).alias('latitude'),
            pl.lit(meta['longitude']).alias('longitude'),
            pl.lit(meta['timezone']).alias('timezone'),
            pl.lit(meta['population']).alias('population'),
        ])
    )
    dfs.append(df)

aqi_df = pl.concat(dfs)

In [35]:
print(weather_df.glimpse())
print("Samples")
print(weather_df.head())

Rows: 62592
Columns: 25
$ time                 <datetime[μs, Asia/Karachi]> 2026-06-02 00:00:00+05:00, 2026-06-02 01:00:00+05:00, 2026-06-02 02:00:00+05:00, 2026-06-02 03:00:00+05:00, 2026-06-02 04:00:00+05:00, 2026-06-02 05:00:00+05:00, 2026-06-02 06:00:00+05:00, 2026-06-02 07:00:00+05:00, 2026-06-02 08:00:00+05:00, 2026-06-02 09:00:00+05:00
$ temperature_2m                              <f64> 29.4, 29.1, 29.0, 28.5, 28.4, 28.2, 28.3, 29.5, 31.1, 33.0
$ relativehumidity_2m                         <i64> 76, 79, 80, 82, 83, 85, 85, 78, 70, 61
$ dewpoint_2m                                 <f64> 24.8, 25.0, 25.1, 25.2, 25.3, 25.4, 25.5, 25.3, 25.1, 24.6
$ apparent_temperature                        <f64> 34.1, 35.0, 34.2, 33.5, 33.8, 33.9, 33.6, 34.4, 35.8, 37.3
$ precipitation                               <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ rain                                        <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ snowfall                                    <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
$ weathercode                                 <i64> 1, 2, 1, 1, 0, 0, 0, 95, 95, 95
$ pressure_msl                                <f64> 1005.9, 1006.4, 1006.0, 1005.8, 1006.1, 1006.7, 1006.5, 1006.5, 1007.0, 1006.8
$ surface_pressure                            <f64> 1004.8, 1005.3, 1004.9, 1004.7, 1005.0, 1005.6, 1005.4, 1005.4, 1005.9, 1005.7
$ cloudcover                                  <i64> 22, 78, 27, 29, 1, 0, 0, 0, 9, 2
$ visibility                                  <f64> 19160.0, 19160.0, 19160.0, 17020.0, 17040.0, 17020.0, 17020.0, 19160.0, 19160.0, 20800.0
$ windspeed_10m                               <f64> 12.9, 5.2, 10.4, 12.7, 10.0, 8.5, 11.3, 13.9, 14.2, 14.8
$ winddirection_10m                           <i64> 223, 176, 195, 205, 219, 207, 205, 210, 235, 226
$ windgusts_10m                               <f64> 22.0, 16.9, 14.4, 9.4, 13.3, 18.4, 17.6, 16.2, 34.6, 33.8
$ uv_index                                    <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.45, 1.55, 3.1
$ is_day                                      <i64> 0, 0, 0, 0, 0, 0, 1, 1, 1, 1
$ geonameid                                   <str> '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161'
$ city                                        <str> 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali'
$ province                                    <str> '05', '05', '05', '05', '05', '05', '05', '05', '05', '05'
$ latitude                                    <f64> 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944
$ longitude                                   <f64> 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298
$ timezone                                    <str> 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi'
$ population                                  <i32> 15781, 15781, 15781, 15781, 15781, 15781, 15781, 15781, 15781, 15781

None
Samples
shape: (5, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ time      ┆ temperatu ┆ relativeh ┆ dewpoint_ ┆ … ┆ latitude ┆ longitude ┆ timezone  ┆ populatio │
│ ---       ┆ re_2m     ┆ umidity_2 ┆ 2m        ┆   ┆ ---      ┆ ---       ┆ ---       ┆ n         │
│ datetime[ ┆ ---       ┆ m         ┆ ---       ┆   ┆ f64      ┆ f64       ┆ str       ┆ ---       │
│ μs, Asia/ ┆ f64       ┆ ---       ┆ f64       ┆   ┆          ┆           ┆           ┆ i32       │
│ Karachi]  ┆           ┆ i64       ┆           ┆   ┆          ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 2026-06-0 ┆ 29.4      ┆ 76        ┆ 24.8      ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Kara ┆ 15781     │
│ 2         ┆           ┆           ┆           ┆   ┆          ┆           ┆ chi       ┆           │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ PKT       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2026-06-0 ┆ 29.1      ┆ 79        ┆ 25.0      ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Kara ┆ 15781     │
│ 2         ┆           ┆           ┆           ┆   ┆          ┆           ┆ chi       ┆           │
│ 01:00:00  ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ PKT       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2026-06-0 ┆ 29.0      ┆ 80        ┆ 25.1      ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Kara ┆ 15781     │
│ 2         ┆           ┆           ┆           ┆   ┆          ┆           ┆ chi       ┆           │
│ 02:00:00  ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ PKT       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2026-06-0 ┆ 28.5      ┆ 82        ┆ 25.2      ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Kara ┆ 15781     │
│ 2         ┆           ┆           ┆           ┆   ┆          ┆           ┆ chi       ┆           │
│ 03:00:00  ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ PKT       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 2026-06-0 ┆ 28.4      ┆ 83        ┆ 25.3      ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Kara ┆ 15781     │
│ 2         ┆           ┆           ┆           ┆   ┆          ┆           ┆ chi       ┆           │
│ 04:00:00  ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ PKT       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [36]:
print(aqi_df.glimpse())
print("Samples")
print(aqi_df.head())

Rows: 62592
Columns: 19
$ time                  <datetime[μs, Asia/Karachi]> 2026-06-02 00:00:00+05:00, 2026-06-02 01:00:00+05:00, 2026-06-02 02:00:00+05:00, 2026-06-02 03:00:00+05:00, 2026-06-02 04:00:00+05:00, 2026-06-02 05:00:00+05:00, 2026-06-02 06:00:00+05:00, 2026-06-02 07:00:00+05:00, 2026-06-02 08:00:00+05:00, 2026-06-02 09:00:00+05:00
$ pm10                                         <f64> 99.0, 78.0, 70.5, 70.1, 74.0, 88.7, 88.0, 80.6, 63.1, 102.2
$ pm2_5                                        <f64> 32.0, 28.0, 26.3, 24.8, 24.8, 26.4, 26.1, 25.5, 25.4, 28.1
$ carbon_monoxide                              <f64> 118.0, 109.0, 102.0, 102.0, 105.0, 107.0, 107.0, 106.0, 106.0, 106.0
$ nitrogen_dioxide                             <f64> 1.3, 1.6, 1.7, 1.7, 1.5, 1.8, 1.4, 0.9, 0.5, 0.3
$ sulphur_dioxide                              <f64> 0.6, 0.5, 0.5, 0.5, 0.5, 0.6, 0.6, 0.6, 0.6, 0.6
$ ozone                                        <f64> 49.0, 47.0, 45.0, 44.0, 45.0, 45.0, 49.0, 54.0, 58.0, 61.0
$ aerosol_optical_depth                        <f64> 0.48, 0.56, 0.6, 0.57, 0.52, 0.6, 0.58, 0.54, 0.54, 0.54
$ dust                                         <f64> 112.0, 89.0, 73.0, 70.0, 75.0, 110.0, 92.0, 69.0, 60.0, 79.0
$ uv_index                                     <f64> 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05, 0.5, 1.7, 3.5
$ european_aqi                                 <i64> 79, 80, 80, 81, 82, 82, 83, 84, 85, 85
$ us_aqi                                       <i64> 82, 84, 85, 86, 87, 87, 88, 89, 90, 90
$ geonameid                                    <str> '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161', '1108161'
$ city                                         <str> 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali', 'Chuhar Jamali'
$ province                                     <str> '05', '05', '05', '05', '05', '05', '05', '05', '05', '05'
$ latitude                                     <f64> 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944, 24.3944
$ longitude                                    <f64> 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298, 67.99298
$ timezone                                     <str> 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi', 'Asia/Karachi'
$ population                                   <i32> 15781, 15781, 15781, 15781, 15781, 15781, 15781, 15781, 15781, 15781

None
Samples
shape: (5, 19)
┌──────────────┬──────┬───────┬──────────────┬───┬──────────┬───────────┬─────────────┬────────────┐
│ time         ┆ pm10 ┆ pm2_5 ┆ carbon_monox ┆ … ┆ latitude ┆ longitude ┆ timezone    ┆ population │
│ ---          ┆ ---  ┆ ---   ┆ ide          ┆   ┆ ---      ┆ ---       ┆ ---         ┆ ---        │
│ datetime[μs, ┆ f64  ┆ f64   ┆ ---          ┆   ┆ f64      ┆ f64       ┆ str         ┆ i32        │
│ Asia/Karachi ┆      ┆       ┆ f64          ┆   ┆          ┆           ┆             ┆            │
│ ]            ┆      ┆       ┆              ┆   ┆          ┆           ┆             ┆            │
╞══════════════╪══════╪═══════╪══════════════╪═══╪══════════╪═══════════╪═════════════╪════════════╡
│ 2026-06-02   ┆ 99.0 ┆ 32.0  ┆ 118.0        ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Karach ┆ 15781      │
│ 00:00:00 PKT ┆      ┆       ┆              ┆   ┆          ┆           ┆ i           ┆            │
│ 2026-06-02   ┆ 78.0 ┆ 28.0  ┆ 109.0        ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Karach ┆ 15781      │
│ 01:00:00 PKT ┆      ┆       ┆              ┆   ┆          ┆           ┆ i           ┆            │
│ 2026-06-02   ┆ 70.5 ┆ 26.3  ┆ 102.0        ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Karach ┆ 15781      │
│ 02:00:00 PKT ┆      ┆       ┆              ┆   ┆          ┆           ┆ i           ┆            │
│ 2026-06-02   ┆ 70.1 ┆ 24.8  ┆ 102.0        ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Karach ┆ 15781      │
│ 03:00:00 PKT ┆      ┆       ┆              ┆   ┆          ┆           ┆ i           ┆            │
│ 2026-06-02   ┆ 74.0 ┆ 24.8  ┆ 105.0        ┆ … ┆ 24.3944  ┆ 67.99298  ┆ Asia/Karach ┆ 15781      │
│ 04:00:00 PKT ┆      ┆       ┆              ┆   ┆          ┆           ┆ i           ┆            │
└──────────────┴──────┴───────┴──────────────┴───┴──────────┴───────────┴─────────────┴────────────┘

In [ ]:
province_map = {
    '02': 'Balochistan',
    '03': 'Khyber Pakhtunkhwa',
    '04': 'Punjab',
    '05': 'Sindh',
    '06': 'Azad Kashmir',
    '07': 'Gilgit-Baltistan',
    '08': 'Islamabad Capital Territory',
}

season_map = {
    1: 'Winter', 2: 'Winter',
    3: 'Spring', 4: 'Spring',
    5: 'Summer', 6: 'Summer',
    7: 'Monsoon', 8: 'Monsoon', 9: 'Monsoon',
    10: 'Autumn', 11: 'Autumn',
    12: 'Winter'
}

day_name_map = {0: 'Monday', 1: 'Tuesday', 2: 'Wednesday',
                3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'}

month_name_map = {1: 'January', 2: 'February', 3: 'March', 4: 'April',
                  5: 'May', 6: 'June', 7: 'July', 8: 'August',
                  9: 'September', 10: 'October', 11: 'November', 12: 'December'}

dim_location = (
    weather_df.select(['geonameid', 'city', 'province', 'latitude', 'longitude', 'population', 'timezone'])
    .unique(subset=['geonameid'])
    .with_columns([
        pl.col('province').replace(province_map).alias('province_name'),
        pl.col('province').alias('province_code'),
    ])
    .drop('province')
    .rename({'city': 'city_name'})
    .with_row_index('location_id', offset=1)
)

print('dim_location:', dim_location.shape)
print(dim_location.columns)
print(dim_location.head(3))

dim_location: (326, 9)
['location_id', 'geonameid', 'city_name', 'latitude', 'longitude', 'population', 'timezone', 'province_name', 'province_code']
shape: (3, 9)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ location_ ┆ geonameid ┆ city_name ┆ latitude ┆ … ┆ populatio ┆ timezone  ┆ province_ ┆ province_ │
│ id        ┆ ---       ┆ ---       ┆ ---      ┆   ┆ n         ┆ ---       ┆ name      ┆ code      │
│ ---       ┆ str       ┆ str       ┆ f64      ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---       │
│ u32       ┆           ┆           ┆          ┆   ┆ i32       ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1         ┆ 1168718   ┆ Okara     ┆ 30.81029 ┆ … ┆ 533693    ┆ Asia/Kara ┆ Punjab    ┆ 04        │
│           ┆           ┆           ┆          ┆   ┆           ┆ chi       ┆           ┆           │
│ 2         ┆ 1166381   ┆ Sakrand   ┆ 26.13845 ┆ … ┆ 31630     ┆ Asia/Kara ┆ Sindh     ┆ 05        │
│           ┆           ┆           ┆          ┆   ┆           ┆ chi       ┆           ┆           │
│ 3         ┆ 1181022   ┆ Chhor     ┆ 25.5126  ┆ … ┆ 16301     ┆ Asia/Kara ┆ Sindh     ┆ 05        │
│           ┆           ┆           ┆          ┆   ┆           ┆ chi       ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [41]:
dim_time = (
    weather_df.select('time')
    .unique()
    .sort('time')
    .rename({'time': 'ts'})
    .with_columns([
        pl.col('ts').dt.date().alias('date'),
        pl.col('ts').dt.year().cast(pl.Int16).alias('year'),
        pl.col('ts').dt.month().cast(pl.Int16).alias('month'),
        pl.col('ts').dt.day().cast(pl.Int16).alias('day'),
        pl.col('ts').dt.hour().cast(pl.Int16).alias('hour'),
        pl.col('ts').dt.weekday().cast(pl.Int16).alias('day_of_week'),
    ])
    .with_columns([
        pl.col('ts').dt.strftime('%B').alias('month_name'),
        pl.col('ts').dt.strftime('%A').alias('day_name'),
        pl.col('day_of_week').is_in([5, 6]).alias('is_weekend'),
        pl.col('month').map_elements(lambda m: season_map[m], return_dtype=pl.String).alias('season'),
    ])
    .with_row_index('time_id', offset=1)
)

print('\ndim_time:', dim_time.shape)
print(dim_time.columns)
print(dim_time.head(3))

dim_time: (192, 12)
['time_id', 'ts', 'date', 'year', 'month', 'day', 'hour', 'day_of_week', 'month_name', 'day_name', 'is_weekend', 'season']
shape: (3, 12)
┌─────────┬───────────────┬────────────┬──────┬───┬────────────┬──────────┬────────────┬────────┐
│ time_id ┆ ts            ┆ date       ┆ year ┆ … ┆ month_name ┆ day_name ┆ is_weekend ┆ season │
│ ---     ┆ ---           ┆ ---        ┆ ---  ┆   ┆ ---        ┆ ---      ┆ ---        ┆ ---    │
│ u32     ┆ datetime[μs,  ┆ date       ┆ i16  ┆   ┆ str        ┆ str      ┆ bool       ┆ str    │
│         ┆ Asia/Karachi] ┆            ┆      ┆   ┆            ┆          ┆            ┆        │
╞═════════╪═══════════════╪════════════╪══════╪═══╪════════════╪══════════╪════════════╪════════╡
│ 1       ┆ 2026-06-02    ┆ 2026-06-02 ┆ 2026 ┆ … ┆ June       ┆ Tuesday  ┆ false      ┆ Summer │
│         ┆ 00:00:00 PKT  ┆            ┆      ┆   ┆            ┆          ┆            ┆        │
│ 2       ┆ 2026-06-02    ┆ 2026-06-02 ┆ 2026 ┆ … ┆ June       ┆ Tuesday  ┆ false      ┆ Summer │
│         ┆ 01:00:00 PKT  ┆            ┆      ┆   ┆            ┆          ┆            ┆        │
│ 3       ┆ 2026-06-02    ┆ 2026-06-02 ┆ 2026 ┆ … ┆ June       ┆ Tuesday  ┆ false      ┆ Summer │
│         ┆ 02:00:00 PKT  ┆            ┆      ┆   ┆            ┆          ┆            ┆        │
└─────────┴───────────────┴────────────┴──────┴───┴────────────┴──────────┴────────────┴────────┘

In [46]:
fact_weather_hourly = (
    weather_df.join(dim_location.select(['geonameid', 'location_id']), on='geonameid', how='left')
    .join(dim_time.select(['ts', 'time_id']), left_on='time', right_on='ts', how='left')
    .drop(['geonameid', 'city', 'province', 'latitude', 'longitude', 'population', 'timezone'])
    .rename({'time': 'ts'})
    .with_columns(pl.col('is_day').cast(pl.Boolean))
    .select([
        'ts', 'location_id', 'time_id',
        'temperature_2m', 'apparent_temperature', 'dewpoint_2m',
        'relativehumidity_2m', 'precipitation', 'rain', 'snowfall',
        'weathercode', 'pressure_msl', 'surface_pressure', 'cloudcover',
        'visibility', 'windspeed_10m', 'winddirection_10m', 'windgusts_10m',
        'uv_index', 'is_day',
    ])
)

print('\nfact_weather_hourly:', fact_weather_hourly.shape)
print(fact_weather_hourly.columns)
print(fact_weather_hourly.head(3))

fact_weather_hourly: (62592, 20)
['ts', 'location_id', 'time_id', 'temperature_2m', 'apparent_temperature', 'dewpoint_2m', 'relativehumidity_2m', 'precipitation', 'rain', 'snowfall', 'weathercode', 'pressure_msl', 'surface_pressure', 'cloudcover', 'visibility', 'windspeed_10m', 'winddirection_10m', 'windgusts_10m', 'uv_index', 'is_day']
shape: (3, 20)
┌────────────┬────────────┬─────────┬────────────┬───┬────────────┬────────────┬──────────┬────────┐
│ ts         ┆ location_i ┆ time_id ┆ temperatur ┆ … ┆ winddirect ┆ windgusts_ ┆ uv_index ┆ is_day │
│ ---        ┆ d          ┆ ---     ┆ e_2m       ┆   ┆ ion_10m    ┆ 10m        ┆ ---      ┆ ---    │
│ datetime[μ ┆ ---        ┆ u32     ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64      ┆ bool   │
│ s, Asia/Ka ┆ u32        ┆         ┆ f64        ┆   ┆ i64        ┆ f64        ┆          ┆        │
│ rachi]     ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
╞════════════╪════════════╪═════════╪════════════╪═══╪════════════╪════════════╪══════════╪════════╡
│ 2026-06-02 ┆ 166        ┆ 1       ┆ 29.4       ┆ … ┆ 223        ┆ 22.0       ┆ 0.0      ┆ false  │
│ 00:00:00   ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
│ PKT        ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
│ 2026-06-02 ┆ 166        ┆ 2       ┆ 29.1       ┆ … ┆ 176        ┆ 16.9       ┆ 0.0      ┆ false  │
│ 01:00:00   ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
│ PKT        ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
│ 2026-06-02 ┆ 166        ┆ 3       ┆ 29.0       ┆ … ┆ 195        ┆ 14.4       ┆ 0.0      ┆ false  │
│ 02:00:00   ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
│ PKT        ┆            ┆         ┆            ┆   ┆            ┆            ┆          ┆        │
└────────────┴────────────┴─────────┴────────────┴───┴────────────┴────────────┴──────────┴────────┘

In [49]:
fact_aqi_hourly = (
    aqi_df
    .join(dim_location.select(['geonameid', 'location_id']), on='geonameid', how='left')
    .join(dim_time.select(['ts', 'time_id']), left_on='time', right_on='ts', how='left')
    .drop(['geonameid', 'city', 'province', 'latitude', 'longitude', 'population', 'timezone'])
    .rename({'time': 'ts'})
    .select([
        'ts', 'location_id', 'time_id',
        'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide',
        'sulphur_dioxide', 'ozone', 'aerosol_optical_depth', 'dust',
        'uv_index', 'european_aqi', 'us_aqi',
    ])
)

print('\nfact_aqi_hourly:', fact_aqi_hourly.shape)
print(fact_aqi_hourly.columns)
print(fact_aqi_hourly.head(3))

fact_aqi_hourly: (62592, 14)
['ts', 'location_id', 'time_id', 'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'aerosol_optical_depth', 'dust', 'uv_index', 'european_aqi', 'us_aqi']
shape: (3, 14)
┌───────────────┬─────────────┬─────────┬──────┬───┬───────┬──────────┬──────────────┬────────┐
│ ts            ┆ location_id ┆ time_id ┆ pm10 ┆ … ┆ dust  ┆ uv_index ┆ european_aqi ┆ us_aqi │
│ ---           ┆ ---         ┆ ---     ┆ ---  ┆   ┆ ---   ┆ ---      ┆ ---          ┆ ---    │
│ datetime[μs,  ┆ u32         ┆ u32     ┆ f64  ┆   ┆ f64   ┆ f64      ┆ i64          ┆ i64    │
│ Asia/Karachi] ┆             ┆         ┆      ┆   ┆       ┆          ┆              ┆        │
╞═══════════════╪═════════════╪═════════╪══════╪═══╪═══════╪══════════╪══════════════╪════════╡
│ 2026-06-02    ┆ 166         ┆ 1       ┆ 99.0 ┆ … ┆ 112.0 ┆ 0.0      ┆ 79           ┆ 82     │
│ 00:00:00 PKT  ┆             ┆         ┆      ┆   ┆       ┆          ┆              ┆        │
│ 2026-06-02    ┆ 166         ┆ 2       ┆ 78.0 ┆ … ┆ 89.0  ┆ 0.0      ┆ 80           ┆ 84     │
│ 01:00:00 PKT  ┆             ┆         ┆      ┆   ┆       ┆          ┆              ┆        │
│ 2026-06-02    ┆ 166         ┆ 3       ┆ 70.5 ┆ … ┆ 73.0  ┆ 0.0      ┆ 80           ┆ 85     │
│ 02:00:00 PKT  ┆             ┆         ┆      ┆   ┆       ┆          ┆              ┆        │
└───────────────┴─────────────┴─────────┴──────┴───┴───────┴──────────┴──────────────┴────────┘

In [50]:
fact_weather_hourly.select('winddirection_10m')

shape: (62_592, 1)
┌───────────────────┐
│ winddirection_10m │
│ ---               │
│ i64               │
╞═══════════════════╡
│ 223               │
│ 176               │
│ 195               │
│ 205               │
│ 219               │
│ …                 │
│ 146               │
│ 81                │
│ 87                │
│ 76                │
│ 38                │
└───────────────────┘

In [1]:
pk_cities_sample = [
    {'geonameid': gid, 'province': city['admin1code'], 'city': city['name']}
    for gid, city in all_cities.items()
    if city['countrycode'] == 'PK'
]
# print unique province codes
unique_codes = set(c['province'] for c in pk_cities_sample)
print(sorted(unique_codes))

NameError: name 'all_cities' is not defined